### ISSUE TITLE
methode showConversationsListFragment does not work 

### ISSUE THREAD

**Issue by VirgileDjimgou** [chat21/chat21-android-sdk#11]
i can not start a chat inside a container   in your demo app 
        // starts the chat inside a container
        ChatManager.getInstance().showConversationsListFragment(getChildFragmentManager(), R.id.container);   cannot** resolve this methode  ....

**Comment by stefanodp91** [comment]
with the last version the method 

`showConversationsListFragment(<FRAGMENT_MANAGER>,<CONTAINER_ID>);  `

was renamed to 

` openConversationsListFragment(<FRAGMENT_MANAGER>,<CONTAINER_ID>); `

so you can call ii with 

` ChatManager.getInstance().openConversationsListFragment(getChildFragmentManager(), R.id.container); `
