### ISSUE TITLE
Android sdk 

### ISSUE THREAD

**Issue by Arthimediaworks** [chat21/chat21-android-sdk#12]
Hello sir,,,,I want the app for developing........But run the code successfully......you didn't mention which activity is first launch......I write code for launch in login acitvity......login and signup is success........But the app is closed automatically after the login and signup page.......

Please help me to clear and run the app success..............

**Comment by andrealeo83** [comment]
Could you send me the exceptions you find on the android studio after the app crash?

**Comment by Arthimediaworks** [comment]
java.lang.RuntimeException: instance cannot be null. call start first. at com.example.amw.chatheat.core.ChatManager.getInstance(ChatManager.java:409)

**Comment by andrealeo83** [comment]
Please use our android demo app available here to start a new project https://github.com/chat21/chat21-android-demo

**Comment by andrealeo83** [comment]
Also please follow this tutorial to start a new project http://www.chat21.org/docs/android/get-started/

**Comment by Arthimediaworks** [comment]
I am using android demo app.....but it does not have chat manager activity.....How to run without chat manager.....help me to run the app successfully...........

**Comment by andrealeo83** [comment]
please share your project on your github repository with me. I will review your code.

**Comment by Arthimediaworks** [comment]
problem  https://github.com/chat21/chat21-android-demo in this code.......please review the code and tell me the solution..........

**Comment by andrealeo83** [comment]
please make a git pull of your repository. We have changed the default branch from Mater to "development_2 ".
