### ISSUE TITLE
Chat is not working

### ISSUE THREAD

**Issue by rizwan-dev** [chat21/chat21-android-sdk#13]
I have loggedin using two different user into two different mobile. I am sending message from one user to another. Another user is not able to get the message. Why this is not working?

**Comment by rizwan-dev** [comment]
The user who is sending message is able to see his message with icon not delivered and the recipient is not able to receive the message.

**Comment by andrealeo83** [comment]
Have you installed https://github.com/chat21/chat21-cloud-functions as described on README?

**Comment by andrealeo83** [comment]
Hi @rizwan-dev What's your problem?

**Comment by AxesandGrinds** [comment]
Hi,

I am having the same problem. I have set up two devices with chat 21, they are not able to read each other's messages. Is there any advice you can give?

I have logged in using two different users in two different emulators. I send message from one user to another. Another user is not able to get the message. Please test your sdk and confirm that it is actually working.

**Comment by Grimshire** [comment]
Does anyone have a forked version of this SDK that _is_ working? This would be a lot of wasted effort to get this far and for it not to work.
