### ISSUE TITLE
Could not find design.jar (com.android.support:design:26.1.0) issue

### ISSUE THREAD

**Issue by sapandang** [chat21/chat21-android-sdk#14]
- Android Studio 3.1.2
-  Gradle version 3.4
-  compileSdkVersion 27
-  buildToolsVersion "27.0.3"

was unable to build project by cloning getting 
**Could not find design.jar (com.android.support:design:26.1.0) issue**

Fixed by changing the resolutionStrategy version to 26.+
```

// resolve conflicts
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        // android resolution
        // source : https://stackoverflow.com/questions/43280871/android-getting-manifest-merger-failed-error-after-update-to-new-version-of-grad
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                // details.useVersion '26.1.0'
                details.useVersion '26.+'
            }
        }
```

**Comment by stefanodp91** [comment]
Hi sapandang, 
as described within the readme, this is a common issue.
You have to replace the resolution strategy non inside the Chat21 SDK, but in your own project.
You can get more details [here](https://github.com/chat21/chat21-android-sdk#common-issues)
