### ISSUE TITLE
Login using google

### ISSUE THREAD

**Issue by karthiciist** [chat21/chat21-android-sdk#15]
My app uses google signin from firebase. How to pass user password to the following code :

ChatManager.startWithEmailAndPassword(this, getString(R.string.google_app_id),
                "john@nashville.it", "**123456**", new ChatAuthentication.OnChatLoginCallback() {...........

**Comment by andrealeo83** [comment]
At the moment ChatManager doesn't support Google SignIn. See ChatAuthentication class for extension.

**Comment by Ajeet-Meena** [comment]
How can we add Google and Facebook login with this library? Can you suggest where should we start if we want to integrate?
