### ISSUE TITLE
Why I can't change user image

### ISSUE THREAD

**Issue by BendiRKO** [chat21/chat21-android-sdk#17]
I am trying to change user profile image and it's not working in app demo on playstore and it's not working on project app demo

**Comment by karthiciist** [comment]
You can use any image picker library like [this](https://github.com/nguyenhoanglam/ImagePicker) or [this](https://github.com/esafirm/android-image-picker) to get the image from your user's phone and update the bitmap to firebase storage or any other online storage and get the URL of that image.

Now pass this URL to "imageurl" variable of "contacts" node in my previous answer. Now you will get the profile pic in your app. 

If you want to check it before deploying, manually insert any picture URL in "imageurl" shown in the above image and run your app. You will see the profile pic in your app.

If you are using google signin in your app, just calling firebaseAuth().getCurrentUser().getProfilePic() will return the profile pic url of the current user.

Good luck :)
