### ISSUE TITLE
How can we clear history in message

### ISSUE THREAD

**Issue by vandanabpatel** [chat21/chat21-android-sdk#42]
I do not want to delete whole conversation
is it possible to delete all message and not from conversation?

**Comment by gab-95** [comment]
Hi @vandanabpatel,
the feature you have request is not still available.
Anyway, you can delete single message from your firebase project by selecting folder:

YOUR_PROJECT_NAME/users/USER_ID/message

**Comment by vandanabpatel** [comment]
I added this feature

conversationMessagesHandler.clearMessageHistory(new OnFirebaseListener() {
                                    @Override
                                    public void onSuccess() {
                                        conversationsHandler.updateConversation(ChatManager.getInstance().getConversationsHandler().getById(conversationId),
                                                object_recipient.getUid(),
                                                new ConversationsListener() {
                                                    @Override
                                                    public void onConversationAdded(Conversation conversation, ChatRuntimeException e) {

                                                    }

                                                    @Override
                                                    public void onConversationChanged(Conversation conversation, ChatRuntimeException e) {
                                                        //                        conversationMessagesHandler.deleteMessagesInMemory();
                                                        adapter_chat.notifyDataSetChanged();
                                                    }

                                                    @Override
                                                    public void onConversationRemoved(ChatRuntimeException e) {

                                                    }
                                                });
                                    }

                                    @Override
                                    public void onFailed() {
                                        showExceptionError(mActivity);
                                    }
                                });

public void clearMessageHistory(final OnFirebaseListener listener) {

        // the node of the conversation with conversationId
        DatabaseReference nodeConversation = conversationMessagesNode;

        nodeConversation.removeValue(new DatabaseReference.CompletionListener() {
            @Override
            public void onComplete(DatabaseError databaseError, DatabaseReference databaseReference) {
                if (databaseError == null) {
                    // success
                    messages.clear();
                    listener.onSuccess();
                } else {
                    // errors
                    listener.onFailed();
                }
            }
        });
    }

public void updateConversation(Conversation conversation, final String recipientId, final ConversationsListener conversationsListener) {
        conversationsNode.child(recipientId)
                .child(FirebaseConstant.last_message_text)
                .setValue("");

        conversationsListener.onConversationChanged(conversation, null);
    }

**Comment by vandanabpatel** [comment]
Hi @gab-95 now,, i have implemented this feature..if may you needed 

[clear_history.txt](https://github.com/chat21/chat21-android-sdk/files/4069461/clear_history.txt)

**Comment by gab-95** [comment]
Hi @vandanabpatel ,

thanks for your code. We will evaluate it and implement in upcoming releases.
