### ISSUE TITLE
Chat 21 SDK Issues.

### ISSUE THREAD

**Issue by LokiRathod** [chat21/chat21-android-sdk#43]
When i am adding the Chat21 Dependencies ("implementation 'org.chat21.android:chat21:1.0.15'")
I am getting below error. and My Project is in AndroidX.

Users/userName/.gradle/caches/transforms-2/files-2.1/fb96de9b363d9f480ff6012a7b07edf6/jetified-chat21-1.0.15/res/layout/layout_custom_notification.xml:29: AAPT: error: resource style/TextAppearance.AppCompat.Notification.Title (aka com.testdemo.projectname:style/TextAppearance.AppCompat.Notification.Title) not found.

Please help me here.

**Comment by zaprogrammer** [comment]
> When i am adding the Chat21 Dependencies ("implementation 'org.chat21.android:chat21:1.0.15'")
> I am getting below error. and My Project is in AndroidX.
> 
> Users/userName/.gradle/caches/transforms-2/files-2.1/fb96de9b363d9f480ff6012a7b07edf6/jetified-chat21-1.0.15/res/layout/layout_custom_notification.xml:29: AAPT: error: resource style/TextAppearance.AppCompat.Notification.Title (aka com.testdemo.projectname:style/TextAppearance.AppCompat.Notification.Title) not found.
> 
> Please help me here.

Same here, any solution ?

**Comment by gab-95** [comment]
Hi @zaprogrammer,
try to add this in your style.xml file:

`<style name="TextAppearance.AppCompat.Notification.Title" parent="@android:style/TextAppearance.StatusBar.EventContent.Title"/>`

Tell me if it works properly.

**Comment by LokiRathod** [comment]
Hi @gab-95 , I have tried this, But same issue.

**Comment by zaprogrammer** [comment]
> Hi @zaprogrammer,
> try to add this in your style.xml file:
> 
> `<style name="TextAppearance.AppCompat.Notification.Title" parent="@android:style/TextAppearance.StatusBar.EventContent.Title"/>`
> 
> Tell me if it works properly.

Thanks a lot @gab-95, it worked, just had to duplicate for the Time and Info styles too as below:

```
<style name="TextAppearance.AppCompat.Notification.Title" parent="@android:style/TextAppearance.StatusBar.EventContent.Title" />
    <style name="TextAppearance.AppCompat.Notification.Time" parent="@android:style/TextAppearance.StatusBar.EventContent.Title" />
    <style name="TextAppearance.AppCompat.Notification.Info" parent="@android:style/TextAppearance.StatusBar.EventContent.Title" />
```

Thanks again :)
